name: Deploy

on: push

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
    DEFAULT_BRANCH: ${{ format('refs/heads/{0}', github.event.repository.default_branch) }}

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    build_or_push_image:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Docker Login
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  tags: |
                      type=raw,value=latest,enable=${{ github.ref == env.DEFAULT_BRANCH }}

            - name: Build and push Docker images
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: ${{ github.ref == env.DEFAULT_BRANCH }}
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
